# GET http://localhost:5000

#--------------------------------------------
 
# POST http://localhost:5000/api/user/signup
# Content-Type: application/json

# {
#     "firstName" : "AKSHAY",
#     "lastName" : "SINGH",
#     "email" : "akshaymemail@gmail.com",
#     "username" : "akshaymemail",
#     "password" : "123456"
# }

#--------------------------------------------

# POST http://localhost:5000/api/user/signin
# Content-Type: application/json

# {
#     "email" : "akshaymemail@gmail.com",
#     "password" : "123456"
# }

#------------------------------------------

# POST http://localhost:5000/api/user/profile
# Content-Type: application/json
# Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDdiZmQ1YWQyOTU2YjJiM2NkZjE2ZGIiLCJlbWFpbCI6ImFrc2hheW1lbWFpbEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTYxOTA5NTY5OCwiZXhwIjoxNjIwMzkxNjk4fQ.38n6Y11wWx4yZmCHRKboLIgXtr91XJbEqoqO1k9pq2Y

#----------------------------------------------- 

#  POST http://localhost:5000/api/admin/signup
# Content-Type: application/json

# {
#     "firstName" : "Hungry",
#     "lastName" : "Pussy",
#     "email" : "hungrypussy@gmail.com",
#     "username" : "hungrypussy",
#     "password" : "123456"
# }

#------------------REQUEST VALIDATION----------------------------- 

# POST http://localhost:5000/api/admin/signin
# Content-Type: application/json

# {
#    "email" : "hungrypussy@gmail.com",
#    "password" : "123456"
# }

#-------------------------------------------------

# POST http://localhost:5000/api/admin/signup
#  Content-Type: application/json

# {
#     "firstName" : "Pussy",
#     "lastName" : "Cat",
#     "email" : "pussycat@gmail.com",
#     "username" : "pussycat",
#     "password" : "123456"
# }

#--------------------------------------------

# POST http://localhost:5000/api/user/signin
# Content-Type: application/json

# {
#     "email" : "akshaymemail@gmail.com",
#     "password" : "123456"
# }

#--------------------------------------------
 
# POST http://localhost:5000/api/user/signup
# Content-Type: application/json

# {
#     "firstName" : "Rezwan",
#     "lastName" : "Khan",
#     "email" : "rezwankhan@gmail.com",
#     "username" : "rezwankhan",
#     "password" :"123456"
# }

#--------------------------------------------
 
# POST http://localhost:5000/api/category/create
# Content-Type: application/json
# Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgyODc2M2Y5YTdiNzM0YWMyNDk2NmQiLCJlbWFpbCI6Imh1bmdyeXB1c3N5QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYxOTM0ODUyNiwiZXhwIjoxNjIwNjQ0NTI2fQ.umwFl3fYx40uNkjoLzmSJaRWuMvRRPV71R22cOoB0m8

# {
#     "name" : "Nokia",
#     "parentId" : "608516f9a2622d133c39d8f4"
# }

#--------------------------------------------

# GET http://localhost:5000/api/category/categories

#--------------------------------------------

# POST http://localhost:5000/api/product/create
# Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgyODc2M2Y5YTdiNzM0YWMyNDk2NmQiLCJlbWFpbCI6Imh1bmdyeXB1c3N5QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYxOTQzNzU2MCwiZXhwIjoxNjIwNzMzNTYwfQ.FkvxhT0Smsn-xOmcuODAe2JW8BTEGj8x3FZBRaxHuIY

#--------------------------------------------

POST http://localhost:5000/api/user/cart/addToCart
Content-Type: application/json
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDdiZmQ1YWQyOTU2YjJiM2NkZjE2ZGIiLCJlbWFpbCI6ImFrc2hheW1lbWFpbEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTYxOTUwNzcyNiwiZXhwIjoxNjIwODAzNzI2fQ.agGROPXLJrfEbCG9a8dvRGV_f0tT9SFIOBES5jJCk5c

{
    "cartItem": {
        "product" : "608806a746d4fa1dcc69bb7b",
        "quantity" : "1",
        "price": "13999"
    }
}