//ADMIN LOGIN ACTION TYPES
export const ADMIN_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

// ADMIN LOGOUT ACTION TYPES 
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS'

// ADMIN SIGNUP ACTION TYPES 
export const ADMIN_SIGNUP_REQUEST = 'ADMIN_SIGNUP_REQUEST'
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS'
export const ADMIN_SIGNUP_FAILURE = 'ADMIN_SIGNUP_FAILURE'